package com.vini.movies.ui.theme

import androidx.compose.ui.unit.dp

val EXTRA_LARGE_PADDING = 40.dp
val LARGE_PADDING = 20.dp
val MEDIUM_PADDING = 16.dp
val SMALL_PADDING = 10.dp
val DEFAULT_PADDING = 8.dp
val EXTRA_SMALL_PADDING = 6.dp
val EXTRA_SMALLEST_PADDING = 3.dp

val PAGING_INDICATOR = 10.dp
val PAGING_INDICATOR_SPACE = 8.dp

val MOVIE_ITEM_WIDTH = 150.dp
val MOVIE_ITEM_HEIGHT = 300.dp
val NAME_PLACEHOLDER_HEIGHT = 30.dp
val ABOUT_PLACEHOLDER_HEIGHT = 15.dp
val RATING_PLACEHOLDER_HEIGHT = 20.dp
val NETWORK_ERROR_ICON_HEIGHT = 120.dp
